"""Crop white margins and package NBAI-generated artwork; no diagram drawing."""
import argparse, json
from pathlib import Path
from PIL import Image, ImageChops
from reportlab.pdfgen import canvas
from reportlab.lib.utils import ImageReader

parser=argparse.ArgumentParser()
parser.add_argument('source', type=Path)
args=parser.parse_args()
source=args.source.resolve()
out=source.parent
im=Image.open(source).convert('RGB')
mask=ImageChops.difference(im,Image.new('RGB',im.size,'white')).convert('L').point(lambda p:255 if p>18 else 0)
b=mask.getbbox() or (0,0,*im.size)
pad=26
box=(max(0,b[0]-pad),max(0,b[1]-pad),min(im.width,b[2]+pad),min(im.height,b[3]+pad))
final=im.crop(box)
png=out/'groundedhuman_method_cropped.png'
final.save(png,dpi=(300,300))
preview=final.copy()
preview.thumbnail((2200,1000),Image.Resampling.LANCZOS)
preview.save(out/'preview.png')
pdf=out/'groundedhuman_method.pdf'
scale=0.25
c=canvas.Canvas(str(pdf),pagesize=(final.width*scale,final.height*scale))
c.setTitle('GroundedHuman — Method Figure Design')
c.setSubject('NBAI-generated conceptual method illustration. Cropping and PDF packaging only.')
c.drawImage(ImageReader(final),0,0,width=final.width*scale,height=final.height*scale)
c.showPage();c.save()
info={'source':str(source),'original_size':im.size,'crop_box':box,'output_size':final.size,'png':str(png),'pdf':str(pdf),'postprocessing':'White-margin crop and format export only; diagram artwork generated by NBAI.'}
(out/'export_metadata.json').write_text(json.dumps(info,ensure_ascii=False,indent=2),encoding='utf-8')
print(json.dumps(info,ensure_ascii=False,indent=2))
