#!/usr/bin/env bash
set -euo pipefail

REPO_ROOT="${REPO_ROOT:-/home/zhw/lab_users/xyb/home/projects/vggt-human}"
export REPO_ROOT

export OUTPUT_DIR="${OUTPUT_DIR:-${REPO_ROOT}/outputs/train/smpl_hsi_nlf_gt_smpl_scale_stage1_b12}"

# Speed / capacity knobs. These are intentionally exposed for 80G GPUs.
export CUDA_VISIBLE_DEVICES_VALUE="${CUDA_VISIBLE_DEVICES_VALUE:-6}"
export BATCH_SIZE="${BATCH_SIZE:-12}"
export NUM_WORKERS="${NUM_WORKERS:-12}"
export NLF_INTERNAL_BATCH_SIZE="${NLF_INTERNAL_BATCH_SIZE:-128}"
export MAX_HUMANS="${MAX_HUMANS:-20}"
export NUM_VIEWS="${NUM_VIEWS:-2}"
export EPOCHS="${EPOCHS:-10}"
export LR="${LR:-5e-6}"
export MAX_STEPS_PER_EPOCH="${MAX_STEPS_PER_EPOCH:-0}"

# Stage 1 trains only the HSI scene affine scale/bias branch.
export TRAIN_HSI_SCENE_AFFINE_ONLY="${TRAIN_HSI_SCENE_AFFINE_ONLY:-true}"
export FREEZE_HSI_SCENE_AFFINE="${FREEZE_HSI_SCENE_AFFINE:-false}"
export HSI_SCENE_AFFINE_MODE="${HSI_SCENE_AFFINE_MODE:-per_frame}"
export HSI_SCENE_LOG_SCALE_MIN="${HSI_SCENE_LOG_SCALE_MIN:--5.0}"
export HSI_SCENE_LOG_SCALE_MAX="${HSI_SCENE_LOG_SCALE_MAX:-5.0}"

# GT-visible-SMPL scale teacher. Teacher projection uses dataset K inside the loss.
export HSI_SMPL_SCALE_TEACHER_WEIGHT="${HSI_SMPL_SCALE_TEACHER_WEIGHT:-1.0}"
export HSI_SMPL_SCALE_TEACHER_SOURCE="${HSI_SMPL_SCALE_TEACHER_SOURCE:-vertices}"
export HSI_SMPL_SCALE_TEACHER_USE_BIAS="${HSI_SMPL_SCALE_TEACHER_USE_BIAS:-false}"
export HSI_SMPL_SCALE_TEACHER_VIS_TOL_M="${HSI_SMPL_SCALE_TEACHER_VIS_TOL_M:-0.20}"
export HSI_SMPL_SCALE_TEACHER_WINDOW="${HSI_SMPL_SCALE_TEACHER_WINDOW:-3}"
export HSI_SMPL_SCALE_TEACHER_MAX_POINTS_PER_PERSON="${HSI_SMPL_SCALE_TEACHER_MAX_POINTS_PER_PERSON:-512}"
export HSI_SMPL_SCALE_TEACHER_MIN_POINTS_PER_PERSON="${HSI_SMPL_SCALE_TEACHER_MIN_POINTS_PER_PERSON:-32}"
export HSI_SMPL_SCALE_TEACHER_MIN_VISIBLE_POINTS="${HSI_SMPL_SCALE_TEACHER_MIN_VISIBLE_POINTS:-128}"
export HSI_SMPL_SCALE_TEACHER_MAD_MULT="${HSI_SMPL_SCALE_TEACHER_MAD_MULT:-2.5}"
export HSI_SMPL_SCALE_TEACHER_LOG_LOSS="${HSI_SMPL_SCALE_TEACHER_LOG_LOSS:-false}"
export HSI_SMPL_SCALE_TEACHER_BIAS_REG_WEIGHT="${HSI_SMPL_SCALE_TEACHER_BIAS_REG_WEIGHT:-0.05}"
export HSI_SMPL_SCALE_TEACHER_MAX_Z_M="${HSI_SMPL_SCALE_TEACHER_MAX_Z_M:-20.0}"

# Keep dense GT depth as an optional tiny auxiliary only; default is pure SMPL-scale teacher.
export DEPTH_TEACHER_WEIGHT="${DEPTH_TEACHER_WEIGHT:-0.0}"
export DEPTH_USE_HUMAN_ROI="${DEPTH_USE_HUMAN_ROI:-true}"
export DEPTH_ROI_EXPAND="${DEPTH_ROI_EXPAND:-0.85}"
export DEPTH_MAX_M="${DEPTH_MAX_M:-30.0}"
export DEPTH_ERROR_CLIP_M="${DEPTH_ERROR_CLIP_M:-2.0}"
export DEPTH_MIN_VALID_PIXELS="${DEPTH_MIN_VALID_PIXELS:-2048}"

# Do not move humans in Stage 1. Later stages can reopen these losses.
export ANCHOR_DEPTH_WEIGHT="${ANCHOR_DEPTH_WEIGHT:-0.0}"
export ANCHOR_SCENE_XYZ_WEIGHT="${ANCHOR_SCENE_XYZ_WEIGHT:-0.0}"
export HSI_POSE_WEIGHT="${HSI_POSE_WEIGHT:-0.0}"
export HSI_BETAS_WEIGHT="${HSI_BETAS_WEIGHT:-0.0}"
export HSI_TRANSL_WEIGHT="${HSI_TRANSL_WEIGHT:-0.0}"
export HSI_JOINTS3D_WEIGHT="${HSI_JOINTS3D_WEIGHT:-0.0}"
export HSI_VERTICES_WEIGHT="${HSI_VERTICES_WEIGHT:-0.0}"
export HSI_PROJECTED_J2D_WEIGHT="${HSI_PROJECTED_J2D_WEIGHT:-0.0}"
export HSI_DELTA_REG_WEIGHT="${HSI_DELTA_REG_WEIGHT:-0.0}"
export HSI_NO_WORSE_WEIGHT="${HSI_NO_WORSE_WEIGHT:-0.0}"
export HSI_GATE_REG_WEIGHT="${HSI_GATE_REG_WEIGHT:-0.0}"
export HSI_CONTACT_WEIGHT="${HSI_CONTACT_WEIGHT:-0.0}"
export HSI_FOOT_CONTACT_WEIGHT="${HSI_FOOT_CONTACT_WEIGHT:-0.0}"
export HSI_FOOT_SOLE_CONTACT_WEIGHT="${HSI_FOOT_SOLE_CONTACT_WEIGHT:-0.0}"
export HSI_SUPPORT_PLANE_CONTACT_WEIGHT="${HSI_SUPPORT_PLANE_CONTACT_WEIGHT:-0.0}"
export HSI_TRANSL_VELOCITY_WEIGHT="${HSI_TRANSL_VELOCITY_WEIGHT:-0.0}"
export HSI_JOINTS_VELOCITY_WEIGHT="${HSI_JOINTS_VELOCITY_WEIGHT:-0.0}"
export HSI_JOINTS_ACCELERATION_WEIGHT="${HSI_JOINTS_ACCELERATION_WEIGHT:-0.0}"
export HSI_TEMPORAL_NO_WORSE_WEIGHT="${HSI_TEMPORAL_NO_WORSE_WEIGHT:-0.0}"
export HSI_FOOT_SLIDING_WEIGHT="${HSI_FOOT_SLIDING_WEIGHT:-0.0}"
export HSI_SCENE_SCALE_TEMPORAL_WEIGHT="${HSI_SCENE_SCALE_TEMPORAL_WEIGHT:-0.0}"
export HSI_SCENE_BIAS_TEMPORAL_WEIGHT="${HSI_SCENE_BIAS_TEMPORAL_WEIGHT:-0.0}"
export HSI_ENABLE_TEMPORAL_MOMENTUM="${HSI_ENABLE_TEMPORAL_MOMENTUM:-false}"
export PREDICT_ID_EMBED="${PREDICT_ID_EMBED:-false}"
export ID_WEIGHT="${ID_WEIGHT:-0.0}"

export SAVE_SCOPE="${SAVE_SCOPE:-hsi}"
export SAVE_TOP_K="${SAVE_TOP_K:-3}"
export SAVE_EPOCH_CHECKPOINT="${SAVE_EPOCH_CHECKPOINT:-false}"
export SAVE_OPTIMIZER="${SAVE_OPTIMIZER:-false}"
export MONITOR="${MONITOR:-loss_total}"
export MONITOR_MODE="${MONITOR_MODE:-min}"

export PROGRESS_LOG_KEYS="${PROGRESS_LOG_KEYS:-loss_total,loss_hsi_smpl_scale_teacher,metric_hsi_smpl_scale_teacher_valid_points,metric_hsi_smpl_scale_teacher_scale,metric_hsi_smpl_scale_teacher_pred_scale,metric_hsi_smpl_scale_teacher_l1,metric_hsi_smpl_scale_teacher_rel_l1,metric_hsi_smpl_scale_teacher_log_l1,loss_hsi_depth_teacher,metric_hsi_depth_teacher_l1}"

bash "${REPO_ROOT}/scripts/train/train_smpl_hsi_nlf_provider.sh"
