#!/usr/bin/env bash
set -euo pipefail

REPO_ROOT="${REPO_ROOT:-/home/zhw/lab_users/xyb/home/projects/vggt-human}"
FRAMES_DIR="${FRAMES_DIR:-/home/zhw/xyb_space/emdb/P3/28_outdoor_walk_lunges/images/}"
STAGE2_DIR="${STAGE2_DIR:-${REPO_ROOT}/outputs/train/smpl_hsi_nlf_stage2_human_scene_align_full}"
CHECKPOINT="${CHECKPOINT:-${STAGE2_DIR}/checkpoint_latest.pt}"
SCALE_CHECKPOINT="${SCALE_CHECKPOINT:-${REPO_ROOT}/outputs/train/smpl_hsi_coarse_residual_stratified_v3/checkpoint_top_train_epoch_0005_loss_total_0.009242.pt}"
OUTPUT_DIR="${OUTPUT_DIR:-${REPO_ROOT}/outputs/vis/stage2_walking_coarse_residual_v3}"
FULL_VIEWER_CACHE_OUTPUT="${FULL_VIEWER_CACHE_OUTPUT:-${OUTPUT_DIR}/full_viewer_cache}"
CUDA_VISIBLE_DEVICES_VALUE="${CUDA_VISIBLE_DEVICES_VALUE:-${CUDA_VISIBLE_DEVICES:-0}}"
PORT="${PORT:-8088}"
MAX_FRAMES="${MAX_FRAMES:-200}"
START_INDEX="${START_INDEX:-0}"
END_INDEX="${END_INDEX:--1}"
FRAME_STRIDE="${FRAME_STRIDE:-1}"
FRAME_SAMPLING="${FRAME_SAMPLING:-head}"
SMPL_DISPLAY_FRAMES="${SMPL_DISPLAY_FRAMES:-0}"
DISPLAY_PEOPLE="${DISPLAY_PEOPLE:-0}"

REPO_ROOT="${REPO_ROOT}" \
FRAMES_DIR="${FRAMES_DIR}" \
STAGE2_DIR="${STAGE2_DIR}" \
CHECKPOINT="${CHECKPOINT}" \
SCALE_CHECKPOINT="${SCALE_CHECKPOINT}" \
OUTPUT_DIR="${OUTPUT_DIR}" \
FULL_VIEWER_CACHE_OUTPUT="${FULL_VIEWER_CACHE_OUTPUT}" \
CUDA_VISIBLE_DEVICES_VALUE="${CUDA_VISIBLE_DEVICES_VALUE}" \
PORT="${PORT}" \
MAX_FRAMES="${MAX_FRAMES}" \
START_INDEX="${START_INDEX}" \
END_INDEX="${END_INDEX}" \
FRAME_STRIDE="${FRAME_STRIDE}" \
FRAME_SAMPLING="${FRAME_SAMPLING}" \
SMPL_DISPLAY_FRAMES="${SMPL_DISPLAY_FRAMES}" \
DISPLAY_PEOPLE="${DISPLAY_PEOPLE}" \
SMOKE_ONLY=true \
bash "${REPO_ROOT}/scripts/vis/serve_stage2_walking_coarse_scale_hsi_cascade.sh"
