#!/usr/bin/env bash
set -euo pipefail

REPO_ROOT="${REPO_ROOT:-/home/zhw/lab_users/xyb/home/projects/vggt-human}"
FRAMES_DIR="${FRAMES_DIR:-/home/zhw/xyb_space/emdb/P4/36_outdoor_long_walk/images}"
STAGE2_DIR="${STAGE2_DIR:-${REPO_ROOT}/outputs/train/smpl_hsi_nlf_stage2_human_scene_align_full}"
CHECKPOINT="${CHECKPOINT:-${STAGE2_DIR}/checkpoint_latest.pt}"
SCALE_CHECKPOINT="${SCALE_CHECKPOINT:-${REPO_ROOT}/outputs/train/smpl_hsi_coarse_residual_stratified_v3/checkpoint_top_train_epoch_0005_loss_total_0.009242.pt}"
OUTPUT_DIR="${OUTPUT_DIR:-${REPO_ROOT}/outputs/vis/stage2_emdb_p4_36_long_walk_coarse_residual_v3}"
VIEWER_CACHE_OUTPUT="${VIEWER_CACHE_OUTPUT:-${OUTPUT_DIR}/viewer_cache}"
CUDA_VISIBLE_DEVICES_VALUE="${CUDA_VISIBLE_DEVICES_VALUE:-${CUDA_VISIBLE_DEVICES:-0}}"
PORT="${PORT:-8080}"
MAX_FRAMES="${MAX_FRAMES:-500}"
START_INDEX="${START_INDEX:-0}"
END_INDEX="${END_INDEX:--1}"
INFERENCE_FRAMES="${INFERENCE_FRAMES:-}"
FRAME_STRIDE="${FRAME_STRIDE:-1}"
FRAME_SAMPLING="${FRAME_SAMPLING:-uniform}"
SMPL_DISPLAY_FRAMES="${SMPL_DISPLAY_FRAMES:-50}"
DISPLAY_PEOPLE="${DISPLAY_PEOPLE:-0}"
NLF_DETECTOR_THRESHOLD="${NLF_DETECTOR_THRESHOLD:-0.3}"
CONF_THRESHOLD="${CONF_THRESHOLD:-0.05}"
VIEWER_MODE="${VIEWER_MODE:-3d}"
SMOKE_ONLY="${SMOKE_ONLY:-false}"

REPO_ROOT="${REPO_ROOT}" \
FRAMES_DIR="${FRAMES_DIR}" \
STAGE2_DIR="${STAGE2_DIR}" \
CHECKPOINT="${CHECKPOINT}" \
SCALE_CHECKPOINT="${SCALE_CHECKPOINT}" \
OUTPUT_DIR="${OUTPUT_DIR}" \
VIEWER_CACHE_OUTPUT="${VIEWER_CACHE_OUTPUT}" \
CUDA_VISIBLE_DEVICES_VALUE="${CUDA_VISIBLE_DEVICES_VALUE}" \
PORT="${PORT}" \
MAX_FRAMES="${MAX_FRAMES}" \
START_INDEX="${START_INDEX}" \
END_INDEX="${END_INDEX}" \
INFERENCE_FRAMES="${INFERENCE_FRAMES}" \
FRAME_STRIDE="${FRAME_STRIDE}" \
FRAME_SAMPLING="${FRAME_SAMPLING}" \
SMPL_DISPLAY_FRAMES="${SMPL_DISPLAY_FRAMES}" \
DISPLAY_PEOPLE="${DISPLAY_PEOPLE}" \
NLF_DETECTOR_THRESHOLD="${NLF_DETECTOR_THRESHOLD}" \
CONF_THRESHOLD="${CONF_THRESHOLD}" \
VIEWER_MODE="${VIEWER_MODE}" \
SMOKE_ONLY="${SMOKE_ONLY}" \
bash "${REPO_ROOT}/scripts/vis/serve_stage2_walking_coarse_scale_hsi_cascade.sh"
